# Generated by Django 4.2.3 on 2023-07-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagiaire',
            name='convocation_file',
            field=models.FileField(blank=True, upload_to='convocations/'),
        ),
    ]
