# Generated by Django 4.2.3 on 2023-07-27 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_stagiaire_convocation_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagiaire',
            name='convocation_file',
        ),
        migrations.CreateModel(
            name='Convocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='convocations/')),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.stagiaire')),
            ],
        ),
    ]
