# Generated by Django 4.2.3 on 2023-07-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_stagiaire_convocation_file_convocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagiaire',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
