# Generated by Django 4.2.3 on 2023-07-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_stagiaire_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagiaire',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
    ]
