# Generated by Django 4.2.3 on 2023-08-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_stagiaire_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocation',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
