# Generated by Django 4.2.3 on 2023-08-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_stagiaire_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagiaire',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
