# Generated by Django 4.2.3 on 2023-08-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_stagiaire_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagiaire',
            name='month',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stagiaire',
            name='year',
            field=models.PositiveIntegerField(default=2023),
        ),
    ]
